project_id     = "despliegue-458304"
region         = "europe-southwest1"
app_name       = "mi-aplicacion"
app_namespace  = "mi-aplicacion"
repo_url       = "https://github.com/juarru/devops11a-project-local-deploy'" 
repo_revision  = "main"
repo_path      = "k8s"